import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/Shared/NavBar";
import Footer from "./Components/Shared/Footer";
import AuthProvider from "../services/AuthProvider"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
     
     <body
        
      >
        <AuthProvider>
        <NavBar />
       <div className="min-h-screen">
       {children}
       </div>
       <div className="min-h-full mt-40">
       <Footer />
       </div>
       </AuthProvider>
      </body>
    
    </html>
  );
}
